### ISSUE TITLE
Request: It would be great to extend the networking guide with netplan

### ISSUE THREAD

**Issue by weactivist** [foxlet/macOS-Simple-KVM#165]
Since Ubuntu 18.04 LTS switched to https://netplan.io/ 🙏

**Comment by cHolzberger** [comment]
this is the br0 stuff: 
```
network:
  version: 2
  renderer: networkd
  ethernets:
    enp3s0:
      dhcp4: no
  bridges:
    br0:
      dhcp4: yes
      interfaces:
        - enp3s0
```

tun/tap seems to be on the roadmap still: 

https://trello.com/c/Rk4kHdGg/31-add-support-for-tun-tap-devices
